version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - es
    env_file:
      - .env

  # Postgres database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7-management
    restart: always
    env_file:
      - .env

    ports:
      - "5672:5672"
      - "15672:15672"

  # celery configuration
  celery:
    restart: always
    build:
      context: .
    command: celery -A capstone worker -l info
    volumes:
      - .:/test_celery
    env_file:
      - .env
    depends_on:
      - web
      - rabbit

  # elasticsearch configuration
  es:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - .:/elasticsearch

volumes:
  postgres_data:
