# Generated by Django 4.1.7 on 2023-04-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookuserlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='books.book'),
        ),
    ]
